ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: '*'
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/32
  hosts:
    - host: jumppods.awscb.id
      http:
        paths:
          - path: /
            backend:
              serviceName: jumppod-api
              servicePort: 80
  tls: []