replicaCount: 1

secret:
  enabled: false
  name: ""
  mountPath: {}
  subPath: {}
  readOnly: true
  data: {}

configMap:
  enabled: true
  name: "jumppod-api"
  mountPath: /app/core/config
  readOnly: true
  data:
    .app.config.json : |-
      {
          "AppName": "Commons Service",
          "GRPCTimeout": 10,
          "CacheExpiry": 300,
          "CacheCleanup": 600,
          "DefaultPageLimit": 3,
          "ClientTimeout": 10
      }

image:
  repository: devopscorner/cicd:alpine
  pullPolicy: IfNotPresent  # IfNotPresent -or- Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "jumppod"
fullnameOverride: "jumppod"

serviceAccount:
  create: true
  annotations: {}
  name: jumppod
  namespace: devops-tools

service:
  enabled: true
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ssh
      port: 2222
      targetPort: 22
      protocol: TCP

containers:
  ports:
    - name: http
      containerPort: 80
      protocol: TCP
    - name: ssh
      containerPort: 22
      protocol: TCP

ingress:
  enabled: false
  tls: []

application:
  enabled: true
  env:
    - name: HELM_TEMPLATE_NAME
      value: api

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 140m
    memory: 170Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  enabled: true
  select:
    node: "devopscorner-tools"   # DEV/UAT Cluster

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}