{{- if and .Values.configMap .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Values.serviceAccount.namespace }}
  prodels:
    {{- include "api.prodels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}