{{- $namespace := .Release.Namespace | default "api" | lower  -}}
{{- if .Values.gateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gateway.svcName | lower }}-gateway
  namespace: ${ parameters.namespace }
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        {{- if .Values.gateway.hosts }}
        {{- range .Values.gateway.hosts }}
        - {{ . }}
        {{- end }}
        {{- end }}
      port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        {{- if .Values.gateway.hosts }}
        {{- range .Values.gateway.hosts }}
        - {{ . }}
        {{- end }}
        {{- end }}
      port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        credentialName: {{ .Values.gateway.tls.credentialName }}
        mode: SIMPLE
---
{{- $svcName := .Values.gateway.svcName | default "default" | lower  -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.gateway.tls.credentialName }}
  namespace: istio-system
spec:
  secretName: {{ .Values.gateway.tls.credentialName }}
  dnsNames:
    {{- range .Values.gateway.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
---

{{- end }}