{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "svcrole.serviceAccountName" . }}
  namespace: {{ .Values.serviceAccount.namespace }}
  stagingels:
    {{- include "svcrole.stagingels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
