{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spinnaker-api.fullname" . }}-rbac
subjects:
  - kind: ServiceAccount
    name: {{ include "spinnaker-api.serviceAccountName" . }}
    namespace: ${ parameters.namespace }
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}