---
repositories:
  - name: devopscorner-lab
    url: s3://devopscorner-helm-chart/lab

templates:
  default: &default
    namespace: devops-monitoring
    version: "1.4.0-rc"

releases:
  - name: grafana-oncall
    chart: devopscorner-lab/api
    values:
      - ./grafana-oncall-values.yml
    <<: *default