configMap:
  enabled: true
  name: "jumppod-config"
  mountPath: "/app/core/config"
  filename: "jumppod-conf"
  readOnly: true
  data:
    QUEUE_TYPE: kafka
    REDIS_SERVICES: redis:6379
    PSQL_SERVICES: postgresql:5432
    MYSQL_SERVICES: mysql:3306
    KAFKA_SERVICES: kafka:9092
    ZOOKEEPER_SERVICES: zookeeper:2181

serviceAccount:
  create: false
  annotations: {}
  name: ""
  namespace: devops-tools