---
repositories:
  - name: devopscorner-staging
    url: s3://devopscorner-helm-chart/staging

templates:
  default: &default
    namespace: devops-tools
    version: "1.4.0"

releases:
  - name: jumppod
    chart: devopscorner-staging/api
    values:
      - ./jumppod-values.yml
    <<: *default