apiVersion: v1
kind: Service
metadata:
  name: {{ include "spinnaker-api.fullname" . }}
  namespace: ${ parameters.namespace }
  labels:
    {{- include "spinnaker-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.service }}
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "spinnaker-api.selectorLabels" . | nindent 4 }}
