{{- if and .Values.configMap .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spinnaker-frontend.fullname" . }}
  namespace: ${ parameters.namespace }
  stagingels:
    {{- include "spinnaker-frontend.stagingels" . | nindent 4 }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}