apiVersion: batch/v1
kind: CronJob
metadata:
  name: telnet-10.20.30.40
  namespace: devops-tools
spec:
  schedule: '*/10 0-14 * * 1-5'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: telnet02
              image: devopscorner/cicd:alpine
              command:
                - /bin/sh
                - '-c'
              args:
                - >-
                  DATE=$(date '+%Y-%m-%d %H:%M') ; mkdir /var/log/containers/ ;
                  date | tee /var/log/containers/telnet-$DATE;  /usr/bin/telnet
                  10.20.30.40 443 | tee -a /var/log/containers/telnet-$DATE;
                  cat /var/log/containers/telnet-$DATE;
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
